CREATE TABLE IF NOT EXISTS PRODUCTO 
(
  ID INT NOT NULL AUTO_INCREMENT ,
  REFERENCIA VARCHAR(10) NOT NULL, 
  NOMBRE VARCHAR(50) NOT NULL, 
  DESCRIPCION VARCHAR(200), 
  CANTIDAD INT(4), 
  PRECIO DECIMAL(6, 2),
  PRIMARY KEY (ID)
);